### ISSUE TITLE
AWS Kinesis/Cloudwatch input: Cannot read properties of null (reading 'open')

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog-plugin-integrations#1334]
## Description
When attempting to create the AWS Kinesis/Cloudwatch input, the following error occurs:
`Cannot read properties of null (reading 'open')`.

Note that the Launch Input button needs to be clicked two times to trigger the error. We discovered this while testing https://github.com/Graylog2/graylog-plugin-integrations/pull/1326#pullrequestreview-1385716451, but the error was confirmed to happen on `master` before the PR was merged.

<details>
<summary>
Full error
</summary>

```
ERROR
Cannot read properties of null (reading 'open')
TypeError: Cannot read properties of null (reading 'open')
    at ReactClassComponent._openModal (http://localhost:8080/ca2e8247-src_components_inputs_index_jsx.js:81:28)
    at HTMLUnknownElement.callCallback (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:188:14)
    at Object.invokeGuardedCallbackDev (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:237:16)
    at invokeGuardedCallback (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:292:31)
    at invokeGuardedCallbackAndCatchFirstError (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:306:25)
    at executeDispatch (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:389:3)
    at executeDispatchesInOrder (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:414:5)
    at executeDispatchesAndRelease (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:3278:5)
    at executeDispatchesAndReleaseTopLevel (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:3287:10)
    at forEachAccumulated (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:3259:8)
ERROR
Cannot read properties of null (reading 'open')
TypeError: Cannot read properties of null (reading 'open')
    at ReactClassComponent._openModal (http://localhost:8080/ca2e8247-src_components_inputs_index_jsx.js:81:28)
    at HTMLUnknownElement.callCallback (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:188:14)
    at Object.invokeGuardedCallbackDev (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:237:16)
    at invokeGuardedCallback (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:292:31)
    at invokeGuardedCallbackAndCatchFirstError (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:306:25)
    at executeDispatch (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:389:3)
    at executeDispatchesInOrder (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:414:5)
    at executeDispatchesAndRelease (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:3278:5)
    at executeDispatchesAndReleaseTopLevel (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:3287:10)
    at forEachAccumulated (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:3259:8)
```
</details>

![Apr-14-2023 10-55-59](https://user-images.githubusercontent.com/3423655/232094904-cdd8c677-c6e9-4ff9-a034-cc214f247a8c.gif)

## Steps To Reproduce
Create a new AWS Kinesis/Cloudwatch input. See gif above

## Environment

- Graylog Version: 5.1.0-SNAPSHOT
- Elasticsearch Version:
- MongoDB Version:
- Browser Version: Chrome 112.0.5615.49 (Official Build) (arm64)

**Comment by danotorrey** [comment]
I found one reference to a similar error:
https://github.com/Graylog2/graylog2-server/pull/14648#discussion_r1104581320

**Comment by danotorrey** [comment]
The on-screen error is only displaying in dev (functionality was added recently to display errors on screen in dev that normally only show in the console). So, the error was probably happening before and we just never noticed.

In prod, the only noticeable symptom is that the `Launch new input` has to be clicked twice to start the create flow.
