### ISSUE TITLE
Error due to application not checkpointing on the end of the shard

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog-plugin-integrations#286]
## Description
We are retrieving Windows event logs from a Kinesis stream. This is a local input on node06 and we are seeing many shard errors. This stream had previously been sending around 6000-9000 msg/s, but now it has slowed to almost nothing. Other streams, ones with a much lower message volume appear to be working normally and these shard errors are not appearing in the logs on those nodes. Is this a Graylog issue?

2019-10-03T22:33:17.234Z ERROR [ShutdownTask] Application exception.
java.lang.IllegalArgumentException: Application didn't checkpoint at end of shard shardId-000000000155. Application must checkpoint upon shard end. See ShardRecordProcessor.shardEnded javadocs for more information.
at software.amazon.kinesis.lifecycle.ShutdownTask.call(ShutdownTask.java:110) ~[?:?]
at software.amazon.kinesis.lifecycle.ShardConsumer.executeTask(ShardConsumer.java:327) ~[?:?]
at software.amazon.kinesis.lifecycle.ShardConsumer.lambda$shutdownComplete$3(ShardConsumer.java:306) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]

**Comment by danotorrey** [comment]
See https://support.graylog.com/#ticket/zoom/2767
