### ISSUE TITLE
Threat input for Palo Alto PAN-OS 8.0 not being read

### ISSUE THREAD

**Issue by yazool** [Graylog2/graylog-plugin-integrations#295]
## Description
While traffic and system logs are being read from a firewall running PAN-OS 8.0, graylog is not recording any threat logs sent. 

I have captured a packet that shows that the threat log is being sent correctly:
`553 <14>1 2019-10-07T17:17:05-04:00 HOSTNAME - - - - 1,2019/10/07 17:17:05,009401017766,THREAT,url,1,2019/10/07 17:17:05,IPADDRESS,IPADDRESS,IPADDRESS,IPADDRESS,SECURITYPOLICY,USERNAME,,web-browsing,vsys1,trust,untrust,ethernet1/3,ethernet1/6,Graylog,2019/10/07 17:17:05,34710,1,49670,80,4456,80,0x403000,tcp,block-override,URL,(9999),adult,informational,client-to-server,45398645,0x0,10.0.0.0-10.255.255.255,Czech Republic,0,,0,,,1,,,,,,,,0,0,0,0,0,,HOSTNAME,,,,get,0,,0,,N/A,unknown,AppThreat-0-0,0x0`
## Steps To Reproduce

1. Set up a Palo Alto device to send threat logs ([documentation for 8.0 here](https://docs.paloaltonetworks.com/pan-os/8-0/pan-os-admin/monitoring/use-syslog-for-monitoring/configure-syslog-monitoring.html))
The Syslog Server Profile settings used for our system are
```
- Name: Graylog
- Syslog Server: IPADDRESS
- Transport: TCP
- Port: 5555
- Format: IETF
- Facility: LOG_USER
```
We send all logs with no filters.

2. Set up a Palo Alto Networks TCP Input (TCP) on the graylog server. The message mappings must match the Palo Alto documentation for the version of Pan-OS being used on the firewall. [The 8.0 syslog fields for threat can be found here](https://docs.paloaltonetworks.com/pan-os/8-0/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/threat-log-fields.html). Ours are set up matching the documentation like so:
```
THREAT_TEMPLATE: position,field,type
1,Receive_Time,STRING
2,Serial_Number,STRING
3,Type,STRING
4,Threat_Content_Type,STRING
5,FUTURE_USE,STRING
6,Generated_Time,STRING
7,Source_IP,STRING
8,Destination_IP,STRING
9,NAT_Source_IP,STRING
10,NAT_Destination_IP,STRING
11,Rule_Name,STRING
12,Source_User,STRING
13,Destination_User,STRING
14,Application,STRING
15,Virtual_System,STRING
16,Source_Zone,STRING
17,Destination_Zone,STRING
18,Inbound_Interface,STRING
19,Outbound_Interface,STRING
20,Log_Action,STRING
21,FUTURE_USE,STRING
22,Session_ID,STRING
23,Repeat_Count,STRING
24,Source_Port,STRING
25,Destination_Port,STRING
26,NAT_Source_Port,STRING
27,NAT_Destination_Port,STRING
28,Flags,STRING
29,Protocol,STRING
30,Action,STRING
31,URL_Filename,STRING
32,Threat_ID,STRING
33,Category,STRING
34,Severity,STRING
35,Direction,STRING
36,Sequence_Number,STRING
37,Action_Flags,STRING
38,Source_Location,STRING
39,Destination_Location,STRING
40,FUTURE_USE,STRING
41,Content_Type,STRING
42,PCAP_ID,STRING
43,File_Digest,STRING
44,Cloud,STRING
45,URL_Index,STRING
46,User_Agent,STRING
47,File_Type,STRING
48,X_Forwarded_For,STRING
49,Referrer,STRING
50,Sender,STRING
51,Subject,STRING
52,Recipient,STRING
53,Report_ID,STRING
54,Device_Group_Hierarchy_Level_1,STRING
55,Device_Group_Hierarchy_Level_2,STRING
56,Device_Group_Hierarchy_Level_3,STRING
57,Device_Group_Hierarchy_Level_4,STRING
58,Virtual_System_Name,STRING
59,Device_Name,STRING
60,FUTURE_USE,STRING
61,Source_VM_UUID,STRING
62,Destination_VM_UUID,STRING
63,HTTP_Method,STRING
64,Tunnel_ID_IMSI,STRING
65,Monitor_Tag_IMEI,STRING
66,Parent_Session_ID,STRING
67,Parent_Start_Time,STRING
68,Tunnel_Type,STRING
69,Threat_Category,STRING
70,Content_Version,STRING
71,FUTURE_USE,STRING
```
3. Generate a threat event on the firewall. I find the easiest way to do this is to set the adult category to block and to visit an obviously adult oriented website. Websites blocked due to category are generated as a THREAT event in addition to the TRAFFIC event. You can see if it got logged by going into the URL Filtering log in the monitor tab of the firewall, locating the entry, then clicking the magnifying glass.

4. That's it for our environment. The log definitely gets sent and is received by graylog (as evidenced by the packet capture) but graylog is not saving it.

## Environment

- Graylog Version: 3.1.0+aa5175e
- Elasticsearch Version: 6.8.2
- MongoDB Version: 4.0.12
- Browser Version: Chrome 77.0.3865.90 (Official Build) (64-bit)

**Comment by yazool** [comment]
I found the issue, I believe this can be closed. In the Palo Alto documentation for SYSTEM and TRAFFIC all of the FUTURE_USE fields have numbers - in threat they did not. I checked the server.log and saw an error regarding that field and labeled them appropriately. Now it's reading.

Thank you

**Comment by danotorrey** [comment]
@yazool Thank you for investigating and reporting this issue. 

It would be great if we can fix our default templates for avoid the error. Thanks for identifying that SYSTEM and TRAFFIC have FUTURE_USE as numbers, and THREAT as a string. Is there any official Palo Alto indicating the data type for these fields? I suppose they may be undefined. 

Do you also happen to have a copy of the error message or stacktrace? Also, could you please post the updated fixed template here?

**Comment by yazool** [comment]
@danotorrey For FUTURE_USE they're all marked as strings.

The error message in server.log looks like this:
```
2019-10-14T14:27:36.558Z ERROR [DecodingProcessor] Unable to decode raw message RawMessage{id=c4c5b9d0-ee8e-11e9-9321-000c29323182, journalOffset=49457740, codec=PaloAlto, payloadSize=781, timestamp=2019-10-14T14:27:36.557Z, remoteAddress=/10.10.0.252:56951} on input <5d70087a9fe998020ec414d8>.
2019-10-14T14:27:36.558Z ERROR [DecodingProcessor] Error processing message RawMessage{id=c4c5b9d0-ee8e-11e9-9321-000c29323182, journalOffset=49457740, codec=PaloAlto, payloadSize=781, timestamp=2019-10-14T14:27:36.557Z, remoteAddress=/10.10.0.252:56951}
java.lang.IllegalArgumentException: Multiple entries with same key: FUTURE_USE=2019/10/14 10:27:36 and FUTURE_USE=0
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215) ~[graylog.jar:?]
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209) ~[graylog.jar:?]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:147) ~[graylog.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:110) ~[graylog.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:393) ~[graylog.jar:?]
	at org.graylog.integrations.inputs.paloalto.PaloAltoTypeParser.parseFields(PaloAltoTypeParser.java:89) ~[?:?]
	at org.graylog.integrations.inputs.paloalto.PaloAltoCodec.decode(PaloAltoCodec.java:82) ~[?:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:150) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:91) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:86) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:45) [graylog.jar:?]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

My updated template (keep in mind this is for Pan-OS 8.0 and 8.1, I'm not sure if they've changed) is this:
```
SYSTEM_TEMPLATE: position,field,type
1,Receive_Time,STRING
2,Serial_Number,STRING
3,Type,STRING
4,Content/Threat_Type,STRING
5,FUTURE_USE1,STRING
6,Generated_Time,STRING
7,Virtual_System,STRING
8,Event_ID,STRING
9,Object,STRING
10,FUTURE_USE2,STRING
11,FUTURE_USE3,STRING
12,Module,STRING
13,Severity,STRING
14,Description,STRING
15,Sequence_Number,STRING
16,Action_Flags,STRING
17,Device_Group_Hierarchy_Level_1,STRING
18,Device_Group_Hierarchy_Level_2,STRING
19,Device_Group_Hierarchy_Level_3,STRING
20,Device_Group_Hierarchy_Level_4,STRING
21,Virtual_System_Name,STRING
22,Device_Name,STRING
THREAT_TEMPLATE: position,field,type
1,Receive_Time,STRING
2,Serial_Number,STRING
3,Type,STRING
4,Threat_Content_Type,STRING
5,FUTURE_USE,STRING
6,Generated_Time,STRING
7,Source_IP,STRING
8,Destination_IP,STRING
9,NAT_Source_IP,STRING
10,NAT_Destination_IP,STRING
11,Rule_Name,STRING
12,Source_User,STRING
13,Destination_User,STRING
14,Application,STRING
15,Virtual_System,STRING
16,Source_Zone,STRING
17,Destination_Zone,STRING
18,Inbound_Interface,STRING
19,Outbound_Interface,STRING
20,Log_Action,STRING
21,FUTURE_USE1,STRING
22,Session_ID,STRING
23,Repeat_Count,STRING
24,Source_Port,STRING
25,Destination_Port,STRING
26,NAT_Source_Port,STRING
27,NAT_Destination_Port,STRING
28,Flags,STRING
29,Protocol,STRING
30,Action,STRING
31,URL_Filename,STRING
32,Threat_ID,STRING
33,Category,STRING
34,Severity,STRING
35,Direction,STRING
36,Sequence_Number,STRING
37,Action_Flags,STRING
38,Source_Location,STRING
39,Destination_Location,STRING
40,FUTURE_USE2,STRING
41,Content_Type,STRING
42,PCAP_ID,STRING
43,File_Digest,STRING
44,Cloud,STRING
45,URL_Index,STRING
46,User_Agent,STRING
47,File_Type,STRING
48,X_Forwarded_For,STRING
49,Referrer,STRING
50,Sender,STRING
51,Subject,STRING
52,Recipient,STRING
53,Report_ID,STRING
54,Device_Group_Hierarchy_Level_1,STRING
55,Device_Group_Hierarchy_Level_2,STRING
56,Device_Group_Hierarchy_Level_3,STRING
57,Device_Group_Hierarchy_Level_4,STRING
58,Virtual_System_Name,STRING
59,Device_Name,STRING
60,FUTURE_USE3,STRING
61,Source_VM_UUID,STRING
62,Destination_VM_UUID,STRING
63,HTTP_Method,STRING
64,Tunnel_ID_IMSI,STRING
65,Monitor_Tag_IMEI,STRING
66,Parent_Session_ID,STRING
67,Parent_Start_Time,STRING
68,Tunnel_Type,STRING
69,Threat_Category,STRING
70,Content_Version,STRING
71,FUTURE_USE4,STRING
TRAFFIC_TEMPLATE: position,field,type
1,Receive_Time,STRING
2,Serial_Number,STRING
3,Type,STRING
4,Threat/Content_Type,STRING
5,FUTURE_USE1,STRING
6,Generated_Time,STRING
7,Source_IP,STRING
8,Destination_IP,STRING
9,NAT_Source_IP,STRING
10,NAT_Destination_IP,STRING
11,Rule_Name,STRING
12,Source_User,STRING
13,Destination_User,STRING
14,Application,STRING
15,Virtual_System,STRING
16,Source_Zone,STRING
17,Destination_Zone,STRING
18,Inbound_Interface,STRING
19,Outbound_Interface,STRING
20,Log_Action,STRING
21,FUTURE_USE2,STRING
22,Session_ID,STRING
23,Repeat_Count,STRING
24,Source_Port,STRING
25,Destination_Port,STRING
26,NAT_Source_Port,STRING
27,NAT_Destination_Port,STRING
28,Flags,STRING
29,Protocol,STRING
30,Action,STRING
31,Bytes,STRING
32,Bytes_Sent,STRING
33,Bytes_Received,STRING
34,Packets,STRING
35,Start_Time,STRING
36,Elapsed_Time,STRING
37,Category,STRING
38,FUTURE_USE3,STRING
39,Sequence_Number,STRING
40,Action_Flags,STRING
41,Source_Location,STRING
42,Destination_Location,STRING
43,FUTURE_USE4,STRING
44,Packets_Sent,STRING
45,Packets_Received,STRING
46,Session_End_Reason,STRING
47,Device_Group_Hierarchy_Level_1,STRING
48,Device_Group_Hierarchy_Level_2,STRING
49,Device_Group_Hierarchy_Level_3,STRING
50,Device_Group_Hierarchy_Level_4,STRING
51,Virtual_System_Name,STRING
52,Device_Name,STRING
53,Action_Source,STRING
54,Source_VM_UUID,STRING
55,Destination_VM_UUID,STRING
56,Tunnel_ID/IMSI,STRING
57,Monitor_Tag/IMEI,STRING
58,Parent_Session_ID,STRING
59,Parent_Start_Time,STRING
60,Tunnel_Type,STRING
bind_address: 0.0.0.0
max_message_size: 12097152
number_worker_threads: 2
port: 5555
recv_buffer_size: 2048579
tcp_keepalive: false
tls_cert_file: <empty>
tls_client_auth: disabled
tls_client_auth_cert_file: <empty>
tls_enable: false
tls_key_file: admin
tls_key_password: ********
use_null_delimiter: false
```

**Comment by MumpekPumpa** [comment]
As it appears this issues persist for PAN OS 9.0 on Graylog 3.3.2 using Palo Alto Networks TCP (PAN-OS v9.x) input.

**Comment by bud1979** [comment]
@MumpekPumpa,  Do you have any logs (Graylog System Logs, and/or Palo Threat Logs) to do some debugging and testing?  We have tested against a sample of logs from Palo, which all work as expected, but would be interesting to see the exact error you are seeing on the 9.x input, as we have changed from a template, to a pre-defined schema.

Thank you
