### ISSUE TITLE
Unable to launch IPFIX UDP Input in dev environment

### ISSUE THREAD

**Issue by lingpri** [Graylog2/graylog-plugin-integrations#355]
## Description
Unable to launch IPFIX UDP Input in the development environment.

https://smd-dev.torch.sh/system/inputs

**Http Log:**
builtins.e7981d8a04378c1937f7.js:14 There was an error fetching a resource: cannot POST https://smd-dev.torch.sh/api/system/inputs (500). Additional information: resource ipfix-iana-elements.json not found.

**Comment by lingpri** [comment]
As per @Bernd, we need to use the ClassLoader , while loading the resource.

final URL url = Resources.getResource(NetFlowV9FieldTypeRegistry.class, DEFAULT_DEFINITIONS);

**Comment by lingpri** [comment]
java.lang.IllegalArgumentException: resource ipfix-iana-elements.json relative to org.graylog.integrations.ipfix.codecs.IpfixCodec not found.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:440) ~[guava-25.1-jre.jar:?]
	at com.google.common.io.Resources.getResource(Resources.java:207) ~[guava-25.1-jre.jar:?]
	at org.graylog.integrations.ipfix.codecs.IpfixCodec.<init>(IpfixCodec.java:85) ~[classes/:?]
	at org.graylog.integrations.ipfix.codecs.IpfixCodec$$FastClassByGuice$$aa2cd521.newInstance(<generated>) ~[classes/:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[guice-4.2.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[guice-4.2.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[guice-4.2.0.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) ~[guice-4.2.0.jar:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42) ~[guice-4.2.0.jar:?]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65) ~[guice-4.2.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) ~[guice-4.2.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[guice-4.2.0.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) ~[guice-4.2.0.jar:?]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050) ~[guice-4.2.0.jar:?]
	at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:836) ~[guice-assistedinject-4.2.0.jar:?]
	at com.sun.proxy.$Proxy164.create(Unknown Source) ~[?:?]
	at org.graylog2.shared.inputs.MessageInputFactory.create(MessageInputFactory.java:39) ~[classes/:?]
	at org.graylog2.inputs.InputServiceImpl.getMessageInput(InputServiceImpl.java:373) ~[classes/:?]
	at org.graylog2.inputs.PersistedInputsImpl.iterator(PersistedInputsImpl.java:54) [classes/:?]
	at org.graylog2.shared.inputs.InputLauncher.launchAllPersisted(InputLauncher.java:115) [classes/:?]
	at org.graylog2.shared.initializers.InputSetupService.run(InputSetupService.java:89) [classes/:?]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66) [guava-25.1-jre.jar:?]
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119) [guava-25.1-jre.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by lingpri** [comment]
![ipfixinput_dev](https://user-images.githubusercontent.com/6947168/71739599-83e66600-2e1f-11ea-9400-e05fb84c1aea.png)
