### ISSUE TITLE
Kinesis: The security token included in the request is expired

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog-plugin-integrations#386]
## Description

<summary>
When using Assume Role ARN functionality, the following error occurs after about one hour of the input running. Restarting the input fixes the issue.

Assume Role ARN support was added in release 3.1.4, but this bug exists, which makes it not function correctly.

The security token included in the request is expired
<details> 
2020-02-03 12:07:06,033 ERROR: software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseCoordinator - LeasingException encountered in lease taking thread
software.amazon.kinesis.leases.exceptions.DependencyException: software.amazon.awssdk.services.dynamodb.model.DynamoDbException: The security token included in the request is expired (Service: DynamoDb, Status Code: 400, Request ID:)
        at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseRefresher.list(DynamoDBLeaseRefresher.java:330) ~[graylog-plugin-integrations-3.2.0.jar:?]
        at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseRefresher.listLeases(DynamoDBLeaseRefresher.java:260) ~[graylog-plugin-integrations-3.2.0.jar:?]
        at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseTaker.updateAllLeases(DynamoDBLeaseTaker.java:253) ~[graylog-plugin-integrations-3.2.0.jar:?]
        at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseTaker.takeLeases(DynamoDBLeaseTaker.java:151) ~[graylog-plugin-integrations-3.2.0.jar:?]
        at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseTaker.takeLeases(DynamoDBLeaseTaker.java:119) ~[graylog-plugin-integrations-3.2.0.jar:?]
        at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseCoordinator.runLeaseTaker(DynamoDBLeaseCoordinator.java:254) ~[graylog-plugin-integrations-3.2.0.jar:?]
        at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseCoordinator$TakerRunnable.run(DynamoDBLeaseCoordinator.java:185) [graylog-plugin-integrations-3.2.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: software.amazon.awssdk.services.dynamodb.model.DynamoDbException: The security token included in the request is expired (Service: DynamoDb, Status Code: 400, Request ID: CTIBM25HOFHUJ3COJ3GTE48LK7VV4KQNSO5AEMVJF66Q9ASUAAJG)
        at software.amazon.awssdk.services.dynamodb.model.DynamoDbException$BuilderImpl.build(DynamoDbException.java:95) ~[?:?]
        at software.amazon.awssdk.services.dynamodb.model.DynamoDbException$BuilderImpl.build(DynamoDbException.java:55) ~[?:?]
        at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.unmarshall(AwsJsonProtocolErrorUnmarshaller.java:88) ~[?:?]
        at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.handle(AwsJsonProtocolErrorUnmarshaller.java:63) ~[?:?]
        at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.handle(AwsJsonProtocolErrorUnmarshaller.java:42) ~[?:?]
        at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:88) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[?:1.8.0_201]
        at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:129) ~[?:?]
        at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:171) ~[?:?]
        at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$500(ResponseHandler.java:68) ~[?:?]
        at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:287) ~[?:?]
        at software.amazon.awssdk.thirdparty.com.typesafe.netty.HandlerPublisher.publishMessage(HandlerPublisher.java:362) ~[?:?]
        at software.amazon.awssdk.thirdparty.com.typesafe.netty.HandlerPublisher.flushBuffer(HandlerPublisher.java:304) ~[?:?]
        at software.amazon.awssdk.thirdparty.com.typesafe.netty.HandlerPublisher.receivedDemand(HandlerPublisher.java:258) ~[?:?]
        at software.amazon.awssdk.thirdparty.com.typesafe.netty.HandlerPublisher.access$200(HandlerPublisher.java:41) ~[?:?]
        at software.amazon.awssdk.thirdparty.com.typesafe.netty.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:452) ~[?:?]
        at software.amazon.awssdk.thirdparty.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[?:?]
        at software.amazon.awssdk.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[?:?]
        at software.amazon.awssdk.thirdparty.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) ~[?:?]
        at software.amazon.awssdk.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) ~[?:?]
        at software.amazon.awssdk.thirdparty.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
        ... 1 more
</details>
</summary>

## Steps To Reproduce

Use the Assume Role ARN for the new AWS Kinesis/Cloudwatch integration.

## Environment

- Graylog Version:
- Elasticsearch Version:
- MongoDB Version:
- Browser Version:

**Comment by danotorrey** [comment]
Support reference: https://support.graylog.com/#ticket/zoom/3110

**Comment by danotorrey** [comment]
The implementation of [StsAssumeRoleCredentialsProvider](https://sdk.amazonaws.com/java/api/2.0.0-preview-11/software/amazon/awssdk/services/sts/auth/StsAssumeRoleCredentialsProvider.html) that this integration automatically handles the refreshing of tokens, so it should handle refreshing the expired token manually. 

The cause of this issue might be that credentials are being manually resolved forcefully too early. https://github.com/Graylog2/graylog-plugin-integrations/blob/c3301d843ff8828b457c41505064ad6f7d51a616/src/main/java/org/graylog/integrations/aws/AWSAuthProvider.java#L53

I will attempt to rework the authentication to resolve them earlier.

**Comment by danotorrey** [comment]
I am testing a fix for this issue now.
